#!/bin/bash

function require_apm() {
  running "apm $1"
  if [[ $(apm list --local | grep $1 | head -1 | cut -d' ' -f1) != $1 ]];
    then
      action "apm install $1"
      apm install $1
  fi
  ok
}

yes_or_no "would you like to install atom-beautify?"
if confirmed; then
  require_apm atom-beautify
fi

yes_or_no "would you like to install javascript-snippets?"
if confirmed; then
  require_apm javascript-snippets
fi

yes_or_no "would you like to install language-mips?"
if confirmed; then
  require_apm language-mips
fi

yes_or_no "would you like to install linter?"
if confirmed; then
  require_apm linter
  yes_or_no "would you like to install linter-erb?"
  if confirmed; then
    require_apm linter-erb
  fi
  yes_or_no "would you like to install linter-eslint?"
  if confirmed; then
    require_apm linter-eslint
  fi
  yes_or_no "would you like to install linter-jsonlint?"
  if confirmed; then
    require_apm linter-jsonlint
  fi
  yes_or_no "would you like to install linter-chktex"
  if confirmed; then
    require_apm linter-chktex
  fi
  yes_or_no "would you like to install linter-shellcheck"
  if confirmed; then
    require_apm linter-shellcheck
  fi
  yes_or_no "would you like to install linter-pylint"
  if confirmed; then
    require_apm linter-pylint
  fi
  yes_or_no "would you like to install linter-ruby"
  if confirmed; then
    require_apm linter-ruby
  fi
fi

yes_or_no "would you like to install build-python?"
if confirmed; then
  require_apm build-python
fi

yes_or_no "would you like to install merge-conflicts?"
if confirmed; then
  require_apm merge-conflicts
fi

yes_or_no "would you like to install imdone-atom?"
if confirmed; then
  require_apm imdone-atom
fi

yes_or_no "would you like to install pigments?"
if confirmed; then
  require_apm pigments
fi

yes_or_no "would you like to install todo-show?"
if confirmed; then
  require_apm todo-show
fi

bot "atom packages installed successfully"
