#!/bin/bash

function require_npm() {
  running "npm $*"
  npm list -g --depth 0 | grep $1@ > /dev/null
  if [[ $? != 0 ]]; then
    action "npm install -g $*"
    npm install -g $@
  fi
  ok
}

yes_or_no "would you like to install http-server?"
if confirmed; then
  require_npm http-server
fi

yes_or_no "would you like to install empty-trash-cli?"
if confirmed; then
  require_npm empty-trash-cli=
fi

yes_or_no "would you like to install fkill-cli?"
if confirmed; then
  require_npm fkill-cli
fi

yes_or_no "would you like to install speed-test?"
if confirmed; then
  require_npm speed-test
fi

yes_or_no "would you like to install gh-home?"
if confirmed; then
  require_npm gh-home
fi

yes_or_no "would you like to install pretty-error?"
if confirmed; then
  require_npm pretty-error
fi

bot "your chosen npm packages installed successfully"
